### PR TITLE
Raw output was rendering without whitespace

### PR DESCRIPTION
**Pull request by gpurkins**
I added a bit of HTML to the blob_controller to get whitespace to render properly for easier copy/paste action from the raw screen.

### CODE REVIEW

**Comment by gmarik** [comment]
Hey @gpurkins, thanks for the PR.
Do you by any chance still have a sample file?! 
Will add a test case…

Thanks!

**Comment by gpurkins** [comment]
The way I replicated it was: 

Create a gist
Paste in a ruby file
Name it ending in .rb
Hit "Create Gist"
View it, click raw.
Renders all one on line with no whitespace.

I can probably whip up a test case for this, but I think it has more to do with how the browser displays it. How could we test for that with RSpec?

**Comment by gmarik** [comment]
apparently rendering with `, :content_type => 'text/plain'` fixes issue. As at the moment it's rendering `html` when it should be just "raw" plain text / data

**Comment by gpurkins** [comment]
Nice, much better than my ugly controller hack. Thanks!

**Pull request closed without merging**
